production:
  daily_reminder_processor:
    class: DailyReminderProcessorJob
    queue: default
    schedule: every day at 9am
  
  billing_cycle_generator:
    class: BillingCycleGeneratorJob
    queue: default
    schedule: every day at 1am
    
  billing_cycle_archiver:
    class: BillingCycleArchiverJob
    queue: default
    schedule: every day at 2am

development:
  daily_reminder_processor:
    class: DailyReminderProcessorJob
    queue: default
    schedule: every day at 9am
    
  billing_cycle_generator:
    class: BillingCycleGeneratorJob
    queue: default
    schedule: every day at 1am
    
  billing_cycle_archiver:
    class: BillingCycleArchiverJob
    queue: default
    schedule: every day at 2am
